[package]
name = "fbx_objects_depviz"
version = "0.1.1"
authors = ["Takuma Yoshioka <nu11p0.6477@gmail.com>"]
edition = "2018"

[dependencies]
docopt = "0.7"
fbx_direct = "0.6.4"
regex = "1"
rustc-serialize = "0.3.18"
