[package]
name = "fbx_objects_depviz"
version = "0.1.1"
authors = ["Takuma Yoshioka <nu11p0.6477@gmail.com>"]
edition = "2018"

[dependencies]
fbx_direct = "0.6.4"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "0.2"
